modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Phat"
description='''
Lò phản ứng RBMK dạng multiblock lục giác — end game generator nguy hiểm.
Positive void coefficient, xenon, hiệu ứng đầu graphite AZ-5, vỡ kênh, nổ hơi, corium.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mekanism"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mekanismgenerators"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="bigreactors"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="modern_industrialization"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="oritech"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="allthemodium"
    type="optional"
    versionRange="*"
    ordering="AFTER"
    side="BOTH"
